# Generated by Django 3.2.8 on 2021-11-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=25)),
                ('platform', models.CharField(choices=[('tweeter', 'TWEETER'), ('instagram', 'INSTAGRAM'), ('TELEGRAM', 'TELEGRAM')], default='tweeter', max_length=10)),
            ],
        ),
    ]
