# Generated by Django 3.2.8 on 2022-07-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211106_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('intagram', 'Instagram'), ('telegram', 'Telegram'), ('twitter', 'Twitter')], max_length=20, verbose_name='پلتفرم')),
                ('column', models.CharField(max_length=20, verbose_name='نام ستون')),
                ('req_file', models.FileField(upload_to='documents/', verbose_name='بارگذاری فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
