# Generated by Django 3.2.14 on 2022-08-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='column',
            field=models.CharField(max_length=30, verbose_name='نام ستون'),
        ),
    ]
