# Generated by Django 3.2.14 on 2022-08-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_document_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPNDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=30, verbose_name='نام ستون')),
                ('req_file', models.FileField(upload_to='documents/', verbose_name='بارگذاری فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
